# Site settings
title: Marc Dominik Migge @ GitHub
email: marcmigge@gmx.net
github_username: mdm
twitter_username: mdmigge
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Marc Dominik Migge. I'm a software developer from Cologne, Germany.
  This is my blog and portfolio. You can find mostly programming related
  articles here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mdm.github.io" # the base hostname & protocol for your site
defaults:
  -
    scope:
      path: ""
    values:
      math: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: "/:year/:month/:day/:title/"
  -
    scope:
      path: "projects"
      type: "posts"
    values:
      layout: project
      permalink: "/projects/:title/"
# Build settings
markdown: kramdown
google_analytics: UA-68661393-1
